language = "en"
theme = "dark"
def_volume = 0
win_width = 400
win_height = 100
interval_update_music = 20
interval_volume = 10
interval_move_music = 1000
path_to_music = "C:/Users/asd/Desktop/Kraject/AppPython/PyPyAudioplayer/audio"
current_song = 0
count_musics = 5
btn_volume_up = "up"
btn_volume_down = "down"
btn_music_plus = "right"
btn_music_minus = "left"
