language = "en"
theme = "dark"
def_volume = 0
win_width = 300
win_height = 240
interval_update_music = 25
interval_volume = 10
interval_move_music = 10
path_to_music = ''
current_song = 0
btn_volume_up = 'Ctrl+Up'
btn_volume_down = 'Ctrl+Down'
btn_music_plus = 'Ctrl+Right'
btn_music_minus = 'Ctrl+Left'
