language = "en"
theme = "dark"
def_volume = 25
win_width = 300
win_height = 240
interval_update_music = 24
interval_volume = 10
interval_move_music = 1000
path_to_music = "C:/Users/asd/Desktop/PyPy/PyPyAudioplayer/audio"
current_song = 1
count_musics = 0
btn_volume_up = "up"
btn_volume_down = "down"
btn_music_plus = "right"
btn_music_minus = "left"
