language = "en"
theme = "dark"
def_volume = 0
current_volume = 0
win_width = 280
win_height = 97
interval_update_music = 20
step_volume = 10
step_music = 1000
path_to_music = ""
current_song = 0
count_musics = 5
btn_volume_up = "up"
btn_volume_down = "down"
btn_music_plus = "right"
btn_music_minus = "left"
